feat(kms-support): Adding KMS support + tests for signing an openssh cert with a KMS key
spanio/node-sshpk pull request #1
Opened 2024-09-09 18:06 UTC by sunny-span

2024-09-09 18:15 UTC, JoshM1994 reviewed
A little confused by the giant addition with no attribution (but nice work adding tests for it!)

Mostly nits, consistency and general clean-up

2024-09-09 18:15 UTC, JoshM1994 commented on lib/certificate.js
> -	utils.assertCompatible(issuerKey, PrivateKey, [1, 2], 'issuer key');
Worth adding an explanation as to why this is commented out and/or just removing it entirely?

2024-09-09 18:15 UTC, JoshM1994 commented on lib/certificate.js
> -	utils.assertCompatible(issuerKey, PrivateKey, [1, 2], 'issuer key');
Ditto for the same pattern above

2024-09-09 18:15 UTC, JoshM1994 commented on lib/formats/openssh-cert.js
> +			console.log('signature');
Not sure there should be a console log nested deeply inside this library?

2024-09-09 18:15 UTC, JoshM1994 commented on package.json
> +    "aws-sdk": "^2.1511.0",
peculiar that you're adding aws-sdk v2 and v3... Should definitely standardize on a single one?

2024-09-09 18:15 UTC, JoshM1994 commented on test/kms_cert.js
> +// const fs = require('fs');
?

2024-09-09 18:15 UTC, JoshM1994 commented on test/kms_cert.js
> +// test('create ecdsa signed, loopback', function (t) {
?

2024-09-09 18:15 UTC, JoshM1994 commented on test/kms_cert.js
> +// Copyright 2018 Joyent, Inc.  All rights reserved.
I recognize this is copyright but where did it come from? Probably worth adding a reference here as it's a pretty large change (that I don't believe was written at SPAN?)

2024-09-09 18:15 UTC, JoshM1994 commented on test/kms_cert.js
> +const { KMS } = require('aws-sdk');
Maybe this should use aws-sdk v3 ?

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-kms/Class/KMSClient/

2024-09-09 21:22 UTC, sunny-span commented on package.json
> +    "aws-sdk": "^2.1511.0",
Yeah. Not sure where it is used either.

2024-09-09 21:23 UTC, sunny-span commented on test/kms_cert.js
> +const { KMS } = require('aws-sdk');
This is not used. I can delete this whole business.

2024-09-10 00:39 UTC, sunny-span commented on lib/certificate.js
> -	utils.assertCompatible(issuerKey, PrivateKey, [1, 2], 'issuer key');
It's not going to be a private key if the key passed is a KMS key. I've added a different check.

2024-09-10 01:27 UTC, JoshM1994 requested changes
99% suggestions for improvement that don't need to block but I do think your `listKeys` method is not doing what you expect? (Unless it's purely for debugging)

2024-09-10 01:27 UTC, JoshM1994 commented on lib/formats/auto.js
> +var kms =require('./kms');
```suggestion
var kms = require('./kms');
```

2024-09-10 01:27 UTC, JoshM1994 commented on lib/formats/auto.js
> +var kms =require('./kms');
(for consistency)

2024-09-10 01:27 UTC, JoshM1994 commented on lib/formats/kms.js
> +Object.keys(TYPES).forEach(function (k) { TYPES[TYPES[k]] = k; });
I'm guessing you inherited this but it's not definitely not the cleanest way of populating an object... global variables and modification of an object in a `forEach` is generally a bad pattern

The more javascript-y way would be:

```
const typeMap = { 'user': 1, 'host': 2 }
const reverseTypeMap = Object.entries(typeMap).reduce((accVal, [key, val]) => ({...accVal, [val]: key}), {})
const TYPES = {
    ...typeMap,
    ...reverseTypeMap,
}
```

2024-09-10 01:27 UTC, JoshM1994 commented on lib/formats/kms.js
> +let ECDSA_ALGO = /^ecdsa-sha2-([^@-]+)-cert-v01@openssh.com$/;
```suggestion
const ECDSA_ALGO = /^ecdsa-sha2-([^@-]+)-cert-v01@openssh.com$/;
```

This is never re-assigned from what I can see

2024-09-10 01:27 UTC, JoshM1994 commented on lib/formats/kms.js
> +	return await client.send(command)
This code will return undefined... If you want to return the data, you need to refactor it to:

```
.then(data => {
   console.info(data);
   return data;
})
```

2024-09-10 01:27 UTC, JoshM1994 commented on lib/formats/kms.js
> +			const publicKey = data.PublicKey;
A few suggestions here but don't consider them blocking

```suggestion
		.then(({ PublicKey: publicKey } )=> { => {
```

2024-09-10 01:27 UTC, JoshM1994 commented on lib/formats/kms.js
> +			let sig = Signature.parse(signature, key.type, 'asn1');
```suggestion
			const sig = Signature.parse(signature, key.type, 'asn1');
```

Since you're only modifying properties of an object, you can still `const` this and just re-assign the keys to new values (The current syntax would _let_ you re-assign the entire variable)

2024-09-10 01:27 UTC, JoshM1994 commented on lib/formats/kms.js
> +	}
```suggestion
	const content = [getCertType(cert.subjectKey), blob.toString('base64'), ...(options.comment ? [options.comment] : [])]
	return content.join(' ');
```

🤷

2024-09-10 01:27 UTC, JoshM1994 commented on lib/formats/kms.js
> +	var sig = cert.signatures.openssh;
(I won't try to refactor this: it could be far cleaner and modernized but I don't believe that's a good use of either of our time!)

2024-09-10 01:27 UTC, JoshM1994 commented on lib/formats/kms.js
> +	if (key.type === 'rsa')
Switch case? Or object lookup?

```
switch(key.type) {
   case 'dsa':
    ...
}
```

or 

```
const certTypeMap = {
   'rsa': 'ssh-rsa-cert-v01@openssh.com'
}
if (certTypeMap[key.type]) return  certTypeMap[key.type]
throw new Error
```

2024-09-10 01:27 UTC, JoshM1994 commented on lib/formats/kms.js
> +	const client = new KMSClient({ region: "us-west-2" });
Not sure the region should be hard-coded into something being used as a library?

2024-09-10 01:27 UTC, JoshM1994 commented on lib/formats/kms.js
> +async function read_bkp(buf, options) {
```suggestion
async function readBkp(buf, options) {
```

Why the snake_case?

2024-09-10 01:27 UTC, JoshM1994 commented on lib/formats/kms.js
> +		ec_publickey = pkcs1.readPkcs1('ECDSA', 'public', der)
ditto on the snake_case

2024-09-10 01:27 UTC, JoshM1994 commented on lib/formats/kms.js
> +function signAsync(cert, signer, done) {
this callback syntax is very different to the `async/await` pattern used elsewhere and could likely be modernized with some promisification? (This callback syntax is notoriously complicated to read and debug)

```
const { promisify } = require('util');
```

2024-09-10 01:27 UTC, JoshM1994 commented on lib/utils.js
> +function isValidSigningKey(key) {
Generally a best practice to "define before you use" and hence move `isKmsKey` to be defined before this method

2024-09-10 03:10 UTC, sunny-span commented on lib/formats/kms.js
> +Object.keys(TYPES).forEach(function (k) { TYPES[TYPES[k]] = k; });
I'll do one better. Statically define this.

2024-09-10 03:13 UTC, sunny-span commented on lib/formats/kms.js
> +			const publicKey = data.PublicKey;
I actually like this.

2024-09-10 03:13 UTC, sunny-span commented
I've deleted a ton of code and gotten a little more braver in refactoring code I didn't understand. Hopefully, that doesn't break things.

2024-09-10 16:56 UTC, merged